@startuml
skinparam interface {
  backgroundColor Green
  borderColor black
}

skinparam component {
  FontSize 13
  FontName Courier
  FontColor black
  BorderColor black
  BackgroundColor gold
  ArrowColor #FF6655
}

[prediction-markets] as PM
[authorized] as AU
[market-commons] as MC
[simple-disputes] as SD
[court] as CO #Lightgray
[swaps] as SW
[rikiddo] as RI #Lightgray
[liquidity-mining] as LM #Lightgray
() SwapsAPI
() MarketsAPI
() DisputeAPI
() RikiddoMVPallet
() LiquidityMiningPalletApi

SW -l- SwapsAPI
MC - MarketsAPI
AU - DisputeAPI
SD - DisputeAPI
CO - DisputeAPI
LM - LiquidityMiningPalletApi
RI -r- RikiddoMVPallet
PM .r.> SwapsAPI : use
PM ..> MarketsAPI : use
PM .l.> DisputeAPI : use
PM .d.> LiquidityMiningPalletApi : use
AU ..> MarketsAPI : use
SD ..> MarketsAPI : use
SW .d.> RikiddoMVPallet : use
SW .d.> LiquidityMiningPalletApi : use
@enduml