@startuml
skinparam interface {
  backgroundColor Green
  borderColor black
}

skinparam component {
  FontSize 13
  FontName Courier
  FontColor black
  BorderColor black
  BackgroundColor gold
  ArrowColor #FF6655
}

[prediction-markets] as PM
[authorized] as AU
[market-commons] as MC
[simple-disputes] as SD #Lightgray
[court] as CO #Lightgray
[swaps] as SW
[rikiddo] as RI #Lightgray
[liquidity-mining] as LM #Lightgray
() SwapsAPI
() MarketsAPI
() DisputeAPI
() RikiddoMVPallet
() LiquidityMiningPalletApi

MC - MarketsAPI
AU - DisputeAPI
SD - DisputeAPI
CO - DisputeAPI
LM -r- LiquidityMiningPalletApi
LM .l.> MarketsAPI: use
LM -[hidden]u- RikiddoMVPallet
RI -r- RikiddoMVPallet
PM .r.> SwapsAPI : use
PM ..> MarketsAPI : use
PM .l.> DisputeAPI : use
PM .r.> LiquidityMiningPalletApi : use
AU ..> MarketsAPI : use
CO ..> MarketsAPI : use
SD ..> MarketsAPI : use
SW -l- SwapsAPI
SW ..> RikiddoMVPallet : use
SW .u.> LiquidityMiningPalletApi : use
SW .d.> MarketsAPI : use
@enduml