@startuml
!theme materia

'States
state Active : Market can be traded
state Closed : Trading is over
note left of Closed
  Closed state is not used currently.
  The code logic checks whether the
  market period end was reached.
end note
state CollectingSubsidy : Rikiddo market needs funding
state Disputed: Market outcome is disputed
state InsufficientSubsidy : Market suspended due to insufficient subsidy
state Proposed : Market has to be approved by ApprovalOrigin
state Reported : Market outcome is reported
state Resolved : Market resolved
state Suspended : Trading is temporarily paused
note right of Suspended
  Unused
end note

[*] -[hidden]> Suspended

'Choices
state cpmm_or_rikiddo <<choice>>
state advised_or_proposed_cpmm <<choice>>
state enough_subsidy <<choice>>
state is_period_over <<choice>>

'Create market
[*] --> advised_or_proposed_cpmm : create market
advised_or_proposed_cpmm --> cpmm_or_rikiddo : [creation == MarketCreation::Permissionless]
advised_or_proposed_cpmm --> Proposed : [creation == MarketCreation::Advised]

cpmm_or_rikiddo --> Active : [scoring_rule == ScoringRule::CPMM]
cpmm_or_rikiddo --> CollectingSubsidy : [scoring_rule == ScoringRule::Rikiddo]

'Delete or activate a market
Proposed --> cpmm_or_rikiddo : ApprovalOrigin accepts market
Proposed --> [*] : ApprovalOrigin rejects market

CollectingSubsidy --> enough_subsidy : market trading period starts
enough_subsidy --> Active : [subsidy => MinSubsidy]
enough_subsidy --> InsufficientSubsidy : [subsidy < MinSubsidy]

'Report market
Active --> is_period_over : report
is_period_over --> Reported : [blocknumber/timestamp > market.period.end]
is_period_over --> Active : [blocknumber/timestamp <= market.period.end]

'Dispute or resolve directly
Reported --> Disputed : dispute started within DisputePeriod
Reported --> Resolved : No dispute started within DisputePeriod

'Disputed market resolves
Disputed --> Resolved : DisputePeriod passed after first dispute

@enduml
