ignore:
  # Temporary allowlist until the Polkadot SDK is upgraded and pulls newer crypto/runtime crates.
  - vulnerability: GHSA-c86p-w88r-qvqr
    package:
      name: ring
  - vulnerability: GHSA-4p46-pwfr-66x6
    package:
      name: ring
  - vulnerability: GHSA-c2f5-jxjv-2hh8
    package:
      name: wasmtime
  - vulnerability: GHSA-hc7m-r6v8-hg9q
    package:
      name: wasmtime
  - vulnerability: GHSA-9ghp-w2hm-vfpf
    package:
      name: wasmtime-jit-debug
  # Temporary allowlist for Go stdlib CVEs pulled in via prebuilt esbuild binaries; remove once upstream ships builds with patched Go toolchains.
  - package:
      name: stdlib
    vulnerability: CVE-2023-45288
  - package:
      name: stdlib
    vulnerability: CVE-2024-24787
  - package:
      name: stdlib
    vulnerability: CVE-2024-24784
  - package:
      name: stdlib
    vulnerability: CVE-2024-24791
  - package:
      name: stdlib
    vulnerability: CVE-2023-24531
  - package:
      name: stdlib
    vulnerability: CVE-2024-24783
  - package:
      name: stdlib
    vulnerability: CVE-2023-45289
  - package:
      name: stdlib
    vulnerability: CVE-2023-45290
  - package:
      name: stdlib
    vulnerability: CVE-2024-34156
  - package:
      name: stdlib
    vulnerability: CVE-2024-24785
  - package:
      name: stdlib
    vulnerability: CVE-2024-34158
  - package:
      name: stdlib
    vulnerability: CVE-2024-24790
  - package:
      name: stdlib
    vulnerability: CVE-2024-45336
  - package:
      name: stdlib
    vulnerability: CVE-2024-34155
  - package:
      name: stdlib
    vulnerability: CVE-2024-45341
  - package:
      name: stdlib
    vulnerability: CVE-2025-22871
  - package:
      name: stdlib
    vulnerability: CVE-2025-61723
  - package:
      name: stdlib
    vulnerability: CVE-2025-61725
  - package:
      name: stdlib
    vulnerability: CVE-2025-58185
  - package:
      name: stdlib
    vulnerability: CVE-2025-47907
  - package:
      name: stdlib
    vulnerability: CVE-2025-58186
  - package:
      name: stdlib
    vulnerability: CVE-2025-61724
  - package:
      name: stdlib
    vulnerability: CVE-2025-47912
  - package:
      name: stdlib
    vulnerability: CVE-2025-47906
  - package:
      name: stdlib
    vulnerability: CVE-2025-58187
  - package:
      name: stdlib
    vulnerability: CVE-2025-58188
  - package:
      name: stdlib
    vulnerability: CVE-2025-58189
  - package:
      name: stdlib
    vulnerability: CVE-2025-22866
  - package:
      name: stdlib
    vulnerability: CVE-2025-4673
  - package:
      name: stdlib
    vulnerability: CVE-2025-4674
  - package:
      name: stdlib
    vulnerability: CVE-2025-58183
  - package:
      name: stdlib
    vulnerability: CVE-2025-0913
  - package:
      name: stdlib
    vulnerability: CVE-2024-24789
  # idna GHSA still present in Rust stack; allowlisted until upstream upgrades.
  - vulnerability: GHSA-h97m-ww89-6jmq
    package:
      name: idna
  # tracing-subscriber 0.2.x pulled in via substrate stack; allowlist until upstream bumps to >=0.3.20.
  - vulnerability: GHSA-xwfj-jgwm-7wp5
    package:
      name: tracing-subscriber
