pull_request_rules:
  - name: Auto merge
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - check-success=Coverage
      - check-success=Format
      - check-success=Copyright Notices
      - check-success=Checks (clippy)
      - check-success=Checks (parachain)
      - check-success=Checks (standalone)
      - check-success=Quick check benchmarks
      - check-success=Test standalone build
      - check-success=Test parachain build
      - check-success=Fuzz
      - label=s:accepted
    actions:
      label:
        remove:
          - s:in-progress
          - s:review-needed
      merge:
        method: squash
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request is now in conflicts. Could you fix it @{{author}}? 🙏
        label:
          add:
            - s:revision-needed
          remove:
            - s:accepted
            - s:in-progress
            - s:review-needed

