pull_request_rules:
  - name: Auto merge
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - check-success=Coverage / Coverage (pull_request)
      - check-success=Rust / Format (pull_request)
      - check-success=Rust / Copyright Notices (pull_request)
      - check-success=Rust / Checks (clippy) (pull_request)
      - check-success=Rust / Checks (parachain) (pull_request)
      - check-success=Rust / Checks (standalone) (pull_request)
      - check-success=Rust / Quick check benchmarks (pull_request)
      - check-success=Rust / Test standalone build (pull_request)
      - check-success=Rust / Test parachain build (pull_request)
      - check-success=Rust / Fuzz (pull_request)
      - label=s:accepted
    actions:
      label:
        remove:
          - s:in-progress
          - s:review-needed
      merge:
        method: squash
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request is now in conflicts. Could you fix it @{{author}}? 🙏
        label:
          add:
            - s:revision-needed
          remove:
            - s:accepted
            - s:in-progress
            - s:review-needed

