pull_request_rules:
  - name: Auto merge
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - check-success=format
      - check-success=tests
      - check-success=fuzz
      - check-success=benchmark
      - label=s:accepted
    actions:
      label:
        remove:
          - s:in-progress
          - s:review-needed
      merge:
        method: squash
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request is now in conflicts. Could you fix it @{{author}}? 🙏

