pull_request_rules:
  - name: Auto merge
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - check-success=Coverage
      - check-success=Format
      - check-success=Copyright Notices
      - check-success=Checks (clippy)
      - check-success=Checks (parachain)
      - check-success=Checks (standalone)
      - check-success=Quick check benchmarks
      - check-success=Test standalone build
      - check-success=Test parachain build
      - check-success=Fuzz
      - label=s:accepted
    actions:
      label:
        remove:
          - s:in-progress
          - s:review-needed
      queue:
        merge_method: squash
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request is now in conflicts. Could you fix it @{{author}}? ðŸ™
        label:
          add:
            - s:revision-needed
          remove:
            - s:accepted
            - s:in-progress
            - s:review-needed
  - name: Set in-progress label after changes are pushed
    conditions:
      - commits[-1].author!=mergify[bot]
      - commits[-1].date_committer>=0 days 00:01 ago
    actions:
        label:
          add:
            - s:in-progress
          remove:
            - s:accepted
            - s:available
            - s:blocked
            - s:on-hold
            - s:review-needed
            - s:revision-needed
  - name: Trigger CI after Mergify merged the base branch (fix merge queue)
    conditions:
      - commits[-1].author=mergify[bot]
      - commits[-1].date_committer>=0 days 00:01 ago
      - queue-position=0
    actions:
        label:
          add:
            - s:review-needed
  - name: Remove CI trigger label
    conditions:
      - commits[-1].author=mergify[bot]
      - label=s:review-needed
      - queue-position=0
    actions:
        label:
          remove:
            - s:review-needed

