[package]
name = "zrml-prediction-markets-rpc"
version = "0.1.0"
authors = ["Logan Saether <x@logansaether.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.3.0" }
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"
sp-runtime = "2.0.1"
sp-api = "2.0.1"
sp-blockchain = "2.0.1"
zrml-prediction-markets-runtime-api = { path = "runtime-api" }
