[settings]
provider = "native"
timeout = 1000

[relaychain]
chain = "rococo-local"
default_args = ["--no-hardware-benchmarks", "-lxcm=trace", "--database=paritydb"]
default_command = "./tmp/polkadot"

[[relaychain.nodes]]
name = "charlie"

[[relaychain.nodes]]
name = "bob"

[[parachains]]
id = 2101

[parachains.collator]
args = ["-lxcm=trace"]
command = "../target/release/zeitgeist"
name = "alice"
