[settings]
provider = "native"
timeout = 1000

[relaychain]
chain = "rococo-dev"
default_args = ["--no-hardware-benchmarks", "-lparachain=debug", "--database=paritydb"]
default_command = "./integration-tests/tmp/polkadot"

[[relaychain.nodes]]
name = "charlie"

[[relaychain.nodes]]
name = "bob"

[[parachains]]
id = 2101

[parachains.collator]
args = ["-lparachain=debug"]
command = "./target/release/zeitgeist"
name = "alice"
ws_port = 9966
