[package]
name = "zrml-traits"
version ="0.1.0"
authors = ["Logan Saether <x@logansaether.com>"]
edition = "2018"

[dependencies]
sp-runtime = { version = "2.0.0",  default-features = false }
sp-std = { version = "2.0.0", default-features = false }

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.1'

[features]
default = ["std"]
std = [
    'codec/std',
    'sp-runtime/std',
    'sp-std/std',
]
