// Copyright 2022-2024 Forecasting Technologies LTD.
// Copyright 2021-2022 Zeitgeist PM LLC.
//
// This file is part of Zeitgeist.
//
// Zeitgeist is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// Zeitgeist is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Zeitgeist. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for zrml_combinatorial_tokens
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.0.0
//! DATE: `2025-05-12`, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `msi-pro-b650-s`, CPU: `AMD Ryzen 9 7950X3D 16-Core Processor`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=target/production/wbuild/battery-station-runtime/battery_station_runtime.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=development
// --steps=50
// --repeat=20
// --pallet=zrml_combinatorial_tokens
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --template=./misc/weight_template.hbs
// --header=./HEADER_GPL3
// --output=./zrml/combinatorial-tokens/src/weights.rs

#![allow(unused_parens)]
#![allow(unused_imports)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

///  Trait containing the required functions for weight retrival within
/// zrml_combinatorial_tokens (automatically generated)
pub trait WeightInfoZeitgeist {
    fn split_position_vertical_sans_parent(n: u32, m: u32) -> Weight;
    fn split_position_vertical_with_parent(n: u32, m: u32) -> Weight;
    fn split_position_horizontal(n: u32, m: u32) -> Weight;
    fn merge_position_vertical_sans_parent(n: u32, m: u32) -> Weight;
    fn merge_position_vertical_with_parent(n: u32, m: u32) -> Weight;
    fn merge_position_horizontal(n: u32, m: u32) -> Weight;
    fn redeem_position_sans_parent(n: u32, m: u32) -> Weight;
    fn redeem_position_with_parent(n: u32, m: u32) -> Weight;
}

/// Weight functions for zrml_combinatorial_tokens (automatically generated)
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfoZeitgeist for WeightInfo<T> {
    /// Storage: `MarketCommons::Markets` (r:1 w:0)
    /// Proof: `MarketCommons::Markets` (`max_values`: None, `max_size`: Some(708), added: 3183, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
    /// Storage: `Tokens::Accounts` (r:32 w:32)
    /// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
    /// Storage: `Tokens::TotalIssuance` (r:32 w:32)
    /// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[2, 32]`.
    /// The range of component `m` is `[32, 64]`.
    fn split_position_vertical_sans_parent(n: u32, m: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `441`
        //  Estimated: `4173 + n * (2612 ±0)`
        // Minimum execution time: 3_394_429 nanoseconds.
        Weight::from_parts(3_418_878_000, 4173)
            // Standard Error: 15_799_679
            .saturating_add(Weight::from_parts(1_032_762_449, 0).saturating_mul(n.into()))
            // Standard Error: 7_298_377
            .saturating_add(Weight::from_parts(110_144_725, 0).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 2612).saturating_mul(n.into()))
    }
    /// Storage: `MarketCommons::Markets` (r:1 w:0)
    /// Proof: `MarketCommons::Markets` (`max_values`: None, `max_size`: Some(708), added: 3183, mode: `MaxEncodedLen`)
    /// Storage: `Tokens::Accounts` (r:33 w:33)
    /// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
    /// Storage: `Tokens::TotalIssuance` (r:33 w:33)
    /// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[2, 32]`.
    /// The range of component `m` is `[32, 64]`.
    fn split_position_vertical_with_parent(n: u32, m: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `671`
        //  Estimated: `4173 + n * (2612 ±0)`
        // Minimum execution time: 3_881_059 nanoseconds.
        Weight::from_parts(3_889_148_000, 4173)
            // Standard Error: 17_240_762
            .saturating_add(Weight::from_parts(1_047_551_363, 0).saturating_mul(n.into()))
            // Standard Error: 7_964_059
            .saturating_add(Weight::from_parts(150_307_010, 0).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(2))
            .saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 2612).saturating_mul(n.into()))
    }
    /// Storage: `MarketCommons::Markets` (r:1 w:0)
    /// Proof: `MarketCommons::Markets` (`max_values`: None, `max_size`: Some(708), added: 3183, mode: `MaxEncodedLen`)
    /// Storage: `Tokens::Accounts` (r:33 w:33)
    /// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
    /// Storage: `Tokens::TotalIssuance` (r:33 w:33)
    /// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[2, 32]`.
    /// The range of component `m` is `[32, 64]`.
    fn split_position_horizontal(n: u32, m: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `633`
        //  Estimated: `4173 + n * (2612 ±0)`
        // Minimum execution time: 5_247_868 nanoseconds.
        Weight::from_parts(5_272_017_000, 4173)
            // Standard Error: 18_366_469
            .saturating_add(Weight::from_parts(1_186_048_968, 0).saturating_mul(n.into()))
            // Standard Error: 8_484_059
            .saturating_add(Weight::from_parts(113_766_841, 0).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(2))
            .saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 2612).saturating_mul(n.into()))
    }
    /// Storage: `MarketCommons::Markets` (r:1 w:0)
    /// Proof: `MarketCommons::Markets` (`max_values`: None, `max_size`: Some(708), added: 3183, mode: `MaxEncodedLen`)
    /// Storage: `Tokens::Accounts` (r:32 w:32)
    /// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
    /// Storage: `Tokens::TotalIssuance` (r:32 w:32)
    /// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[2, 32]`.
    /// The range of component `m` is `[32, 64]`.
    fn merge_position_vertical_sans_parent(n: u32, m: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `619 + n * (160 ±0)`
        //  Estimated: `4173 + n * (2612 ±0)`
        // Minimum execution time: 3_371_269 nanoseconds.
        Weight::from_parts(3_442_549_000, 4173)
            // Standard Error: 16_779_984
            .saturating_add(Weight::from_parts(1_084_445_742, 0).saturating_mul(n.into()))
            // Standard Error: 7_751_211
            .saturating_add(Weight::from_parts(106_116_314, 0).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 2612).saturating_mul(n.into()))
    }
    /// Storage: `MarketCommons::Markets` (r:1 w:0)
    /// Proof: `MarketCommons::Markets` (`max_values`: None, `max_size`: Some(708), added: 3183, mode: `MaxEncodedLen`)
    /// Storage: `Tokens::Accounts` (r:33 w:33)
    /// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
    /// Storage: `Tokens::TotalIssuance` (r:33 w:33)
    /// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[2, 32]`.
    /// The range of component `m` is `[32, 64]`.
    fn merge_position_vertical_with_parent(n: u32, m: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `517 + n * (160 ±0)`
        //  Estimated: `4173 + n * (2612 ±0)`
        // Minimum execution time: 3_406_219 nanoseconds.
        Weight::from_parts(3_420_058_000, 4173)
            // Standard Error: 14_383_089
            .saturating_add(Weight::from_parts(1_117_903_088, 0).saturating_mul(n.into()))
            // Standard Error: 6_644_009
            .saturating_add(Weight::from_parts(102_097_775, 0).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(2))
            .saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 2612).saturating_mul(n.into()))
    }
    /// Storage: `MarketCommons::Markets` (r:1 w:0)
    /// Proof: `MarketCommons::Markets` (`max_values`: None, `max_size`: Some(708), added: 3183, mode: `MaxEncodedLen`)
    /// Storage: `Tokens::Accounts` (r:33 w:33)
    /// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
    /// Storage: `Tokens::TotalIssuance` (r:33 w:33)
    /// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[2, 32]`.
    /// The range of component `m` is `[32, 64]`.
    fn merge_position_horizontal(n: u32, m: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `478 + n * (160 ±0)`
        //  Estimated: `4173 + n * (2612 ±0)`
        // Minimum execution time: 5_001_023 nanoseconds.
        Weight::from_parts(5_046_423_000, 4173)
            // Standard Error: 19_266_513
            .saturating_add(Weight::from_parts(1_029_431_871, 0).saturating_mul(n.into()))
            // Standard Error: 8_899_819
            .saturating_add(Weight::from_parts(132_721_642, 0).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(2))
            .saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 2612).saturating_mul(n.into()))
    }
    /// Storage: `MarketCommons::Markets` (r:1 w:0)
    /// Proof: `MarketCommons::Markets` (`max_values`: None, `max_size`: Some(708), added: 3183, mode: `MaxEncodedLen`)
    /// Storage: `Tokens::Accounts` (r:1 w:1)
    /// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
    /// Storage: `Tokens::TotalIssuance` (r:1 w:1)
    /// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[2, 32]`.
    /// The range of component `m` is `[32, 64]`.
    fn redeem_position_sans_parent(_n: u32, m: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `780`
        //  Estimated: `4173`
        // Minimum execution time: 891_069 nanoseconds.
        Weight::from_parts(56_226_984, 4173)
            // Standard Error: 109_128
            .saturating_add(Weight::from_parts(26_921_339, 0).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(3))
    }
    /// Storage: `MarketCommons::Markets` (r:1 w:0)
    /// Proof: `MarketCommons::Markets` (`max_values`: None, `max_size`: Some(708), added: 3183, mode: `MaxEncodedLen`)
    /// Storage: `Tokens::Accounts` (r:2 w:2)
    /// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
    /// Storage: `Tokens::TotalIssuance` (r:2 w:2)
    /// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[2, 32]`.
    /// The range of component `m` is `[32, 64]`.
    fn redeem_position_with_parent(_n: u32, m: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `674`
        //  Estimated: `6214`
        // Minimum execution time: 903_679 nanoseconds.
        Weight::from_parts(908_819_000, 6214)
            // Standard Error: 128_669
            .saturating_add(Weight::from_parts(16_287_221, 0).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(4))
    }
}
