endpoint: wss://basilisk-rococo-rpc.play.hydration.cloud
mock-signature-host: true
block: ${env.BASILISK_BLOCK_NUMBER}
db: ./tmp/basilisk_db_mba.sqlite

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
  Tokens:
    Accounts:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 17
        - free: '100000000000000000000'