endpoint: wss://hydradx-rpc.dwellir.com
mock-signature-host: true
block: ${env.HYDRADX_BLOCK_NUMBER}
db: ./tmp/hydradx_db_mba.sqlite
# wasm-override: hydradx_runtime.compact.compressed.wasm

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
  Tokens:
    Accounts:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 0 # HDX
        - free: '10000000000000000000000000'
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 1 # Lerna
        - free: '100000000000000000000000'
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 2 # DAI Stablecoin (via Wormhole)
        - free: '100000000000000000000000'
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 3 # Wrapped Bitcoin (via Wormhole)
        - free: '100000000000000000000000'
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 4 # Ethereum (via Wormhole)
        - free: '100000000000000000000000'
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 5 # Polkadot
        - free: '100000000000000000000000'
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 6 # ApeCoin (via Wormhole)
        - free: '100000000000000000000000'
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 7 # USD Coin (via Wormhole)
        - free: '100000000000000000000000'
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 8 # Phala
        - free: '100000000000000000000000'
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 9 # Astar
        - free: '100000000000000000000000'
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 10 # Statemint USDT
        - free: '100000000000000000000000'
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 11 # interBTC
        - free: '100000000000000000000000'
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 12 # Zeitgeist
        - free: '100000000000000000000000'
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 13 # Centrifuge
        - free: '100000000000000000000000'
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 14 # Bifrost Native Coin
        - free: '100000000000000000000000'
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 15 # Bifrost Voucher DOT
        - free: '100000000000000000000000'
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 16 # GLMR
        - free: '100000000000000000000000'
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - 17 # Interlay
        - free: '100000000000000000000000'
  TechnicalCommittee:
    Members: ["5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"]
  Council:
    Members: ["5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"]