endpoint: wss://main.rpc.zeitgeist.pm/ws
# endpoint: wss://zeitgeist.api.onfinality.io/public-ws
mock-signature-host: true
db: ./tmp/ztg_db_mba.sqlite
# wasm-override: zeitgeist-runtime.compact.compressed.wasm

import-storage:
    System:
        Account:
            - - - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
              - providers: 1
                data:
                    free: "100000000000000000000000"
    AdvisoryCommittee:
        Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
    AdvisoryCommitteeMembership:
        Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
    Council:
        Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
    CouncilMembership:
        Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
    TechnicalCommittee:
        Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
    TechnicalCommitteeMembership:
        Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
    AuthorFilter:
        EligibleRatio: 100
        EligibleCount: 100
    # Complex working example of storage import
    # AssetRegistry:
    #     Metadata:
    #         - 
    #           - 
    #             - ForeignAsset: 10
    #           - decimals: 6
    #             name: USD Coin
    #             symbol: USDC
    #             existentialDeposit: "10000"
    #             location:
    #                 V3:
    #                     parents: 1
    #                     interior:
    #                         X3: [
    #                             Parachain: 1000,
    #                             PalletInstance: 50,
    #                             GeneralIndex: 1337,
    #                         ]
    #             additional:
    #                 xcm:
    #                     feeFactor: null
    #                 allowAsBaseAsset: false