[settings]
timeout = 1000
provider = "native"

[relaychain]
chain = "rococo-dev"
default_command = "./tmp/polkadot"
default_args = [ "--no-hardware-benchmarks", "-lparachain=debug", "--database=paritydb" ]

  [[relaychain.nodes]]
  name = "charlie"

  [[relaychain.nodes]]
  name = "bob"

[[parachains]]
id = 2101

  [parachains.collator]
  name = "alice"
  command = "./target/debug/zeitgeist"
  args = ["-lparachain=debug"]
  ws_port = 9944