[[bin]]
doc = false
name = "deploy_combinatorial_pool"
path = "deploy_combinatorial_pool.rs"
test = false

[[bin]]
doc = false
name = "combo_buy"
path = "combo_buy.rs"
test = false

[[bin]]
doc = false
name = "combo_sell"
path = "combo_sell.rs"
test = false

[dependencies]
arbitrary = { workspace = true, features = ["derive"] }
frame-support = { workspace = true, features = ["default"] }
frame-system = { workspace = true }
libfuzzer-sys = { workspace = true }
orml-traits = { workspace = true, features = ["default"] }
rand = { workspace = true, features = ["default"] }
sp-runtime = { workspace = true, features = ["default"] }
zeitgeist-primitives = { workspace = true, features = ["default", "mock"] }
zrml-neo-swaps = { workspace = true, features = ["default", "mock"] }

[package]
authors = ["Forecasting Technologies Ltd"]
edition.workspace = true
name = "zrml-neo-swaps-fuzz"
publish = false
version = "0.6.1"

[package.metadata]
cargo-fuzz = true
