// Copyright 2021-2022 Zeitgeist PM LLC.
//
// This file is part of Zeitgeist.
//
// Zeitgeist is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// Zeitgeist is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Zeitgeist. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for pallet_membership
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-12-15, STEPS: `2`, REPEAT: 0, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Native), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/zeitgeist
// benchmark
// pallet
// --chain=dev
// --steps=2
// --repeat=0
// --pallet=pallet_membership
// --extrinsic=*
// --execution=native
// --detailed-log-output
// --wasm-execution=compiled
// --heap-pages=4096
// --template=./misc/frame_weight_template.hbs
// --output=./runtime/common/src/weights/

#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for pallet_membership (automatically generated)
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_membership::weights::WeightInfo for WeightInfo<T> {
    // Storage: AdvisoryCommitteeMembership Members (r:1 w:1)
    // Storage: AdvisoryCommittee Proposals (r:1 w:0)
    // Storage: AdvisoryCommittee Members (r:0 w:1)
    // Storage: AdvisoryCommittee Prime (r:0 w:1)
    fn add_member(_m: u32) -> Weight {
        Weight::from_ref_time(27_012_000 as u64)
            .saturating_add(T::DbWeight::get().reads(2 as u64))
            .saturating_add(T::DbWeight::get().writes(3 as u64))
    }
    // Storage: AdvisoryCommitteeMembership Members (r:1 w:1)
    // Storage: AdvisoryCommittee Proposals (r:1 w:0)
    // Storage: AdvisoryCommitteeMembership Prime (r:1 w:0)
    // Storage: AdvisoryCommittee Members (r:0 w:1)
    // Storage: AdvisoryCommittee Prime (r:0 w:1)
    fn remove_member(_m: u32) -> Weight {
        Weight::from_ref_time(27_303_000 as u64)
            .saturating_add(T::DbWeight::get().reads(3 as u64))
            .saturating_add(T::DbWeight::get().writes(3 as u64))
    }
    // Storage: AdvisoryCommitteeMembership Members (r:1 w:1)
    // Storage: AdvisoryCommittee Proposals (r:1 w:0)
    // Storage: AdvisoryCommitteeMembership Prime (r:1 w:0)
    // Storage: AdvisoryCommittee Members (r:0 w:1)
    // Storage: AdvisoryCommittee Prime (r:0 w:1)
    fn swap_member(_m: u32) -> Weight {
        Weight::from_ref_time(34_036_000 as u64)
            .saturating_add(T::DbWeight::get().reads(3 as u64))
            .saturating_add(T::DbWeight::get().writes(3 as u64))
    }
    // Storage: AdvisoryCommitteeMembership Members (r:1 w:1)
    // Storage: AdvisoryCommittee Proposals (r:1 w:0)
    // Storage: AdvisoryCommitteeMembership Prime (r:1 w:0)
    // Storage: AdvisoryCommittee Members (r:0 w:1)
    // Storage: AdvisoryCommittee Prime (r:0 w:1)
    fn reset_member(_m: u32) -> Weight {
        Weight::from_ref_time(40_588_000 as u64)
            .saturating_add(T::DbWeight::get().reads(3 as u64))
            .saturating_add(T::DbWeight::get().writes(3 as u64))
    }
    // Storage: AdvisoryCommitteeMembership Members (r:1 w:1)
    // Storage: AdvisoryCommittee Proposals (r:1 w:0)
    // Storage: AdvisoryCommitteeMembership Prime (r:1 w:1)
    // Storage: AdvisoryCommittee Members (r:0 w:1)
    // Storage: AdvisoryCommittee Prime (r:0 w:1)
    fn change_key(_m: u32) -> Weight {
        Weight::from_ref_time(44_596_000 as u64)
            .saturating_add(T::DbWeight::get().reads(3 as u64))
            .saturating_add(T::DbWeight::get().writes(4 as u64))
    }
    // Storage: AdvisoryCommitteeMembership Members (r:1 w:0)
    // Storage: AdvisoryCommitteeMembership Prime (r:0 w:1)
    // Storage: AdvisoryCommittee Prime (r:0 w:1)
    fn set_prime(_m: u32) -> Weight {
        Weight::from_ref_time(19_618_000 as u64)
            .saturating_add(T::DbWeight::get().reads(1 as u64))
            .saturating_add(T::DbWeight::get().writes(2 as u64))
    }
    // Storage: AdvisoryCommitteeMembership Prime (r:0 w:1)
    // Storage: AdvisoryCommittee Prime (r:0 w:1)
    fn clear_prime(_m: u32) -> Weight {
        Weight::from_ref_time(9_869_000 as u64).saturating_add(T::DbWeight::get().writes(2 as u64))
    }
}
