// Copyright 2022-2023 Forecasting Technologies LTD.
// Copyright 2021-2022 Zeitgeist PM LLC.
//
// This file is part of Zeitgeist.
//
// Zeitgeist is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// Zeitgeist is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Zeitgeist. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for pallet_membership
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: `2023-09-19`, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `zeitgeist-benchmark`, CPU: `AMD EPYC 7601 32-Core Processor`
//! EXECUTION: `Some(Wasm)`, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/production/zeitgeist
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_membership
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --template=./misc/frame_weight_template.hbs
// --header=./HEADER_GPL3
// --output=./runtime/common/src/weights/

#![allow(unused_parens)]
#![allow(unused_imports)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for pallet_membership (automatically generated)
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_membership::weights::WeightInfo for WeightInfo<T> {
    /// Storage: AdvisoryCommitteeMembership Members (r:1 w:1)
    /// Proof: AdvisoryCommitteeMembership Members (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
    /// Storage: AdvisoryCommittee Proposals (r:1 w:0)
    /// Proof Skipped: AdvisoryCommittee Proposals (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: AdvisoryCommittee Members (r:0 w:1)
    /// Proof Skipped: AdvisoryCommittee Members (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: AdvisoryCommittee Prime (r:0 w:1)
    /// Proof Skipped: AdvisoryCommittee Prime (max_values: Some(1), max_size: None, mode: Measured)
    fn add_member(m: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `237 + m * (64 ±0)`
        //  Estimated: `4900 + m * (192 ±0)`
        // Minimum execution time: 28_290 nanoseconds.
        Weight::from_parts(35_685_233, 4900)
            // Standard Error: 9_824
            .saturating_add(Weight::from_ref_time(79_139).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
            .saturating_add(Weight::from_proof_size(192).saturating_mul(m.into()))
    }
    /// Storage: AdvisoryCommitteeMembership Members (r:1 w:1)
    /// Proof: AdvisoryCommitteeMembership Members (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
    /// Storage: AdvisoryCommittee Proposals (r:1 w:0)
    /// Proof Skipped: AdvisoryCommittee Proposals (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: AdvisoryCommitteeMembership Prime (r:1 w:0)
    /// Proof: AdvisoryCommitteeMembership Prime (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
    /// Storage: AdvisoryCommittee Members (r:0 w:1)
    /// Proof Skipped: AdvisoryCommittee Members (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: AdvisoryCommittee Prime (r:0 w:1)
    /// Proof Skipped: AdvisoryCommittee Prime (max_values: Some(1), max_size: None, mode: Measured)
    fn remove_member(m: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `341 + m * (64 ±0)`
        //  Estimated: `5739 + m * (192 ±0)`
        // Minimum execution time: 33_260 nanoseconds.
        Weight::from_parts(40_001_420, 5739)
            // Standard Error: 4_422
            .saturating_add(Weight::from_ref_time(55_502).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
            .saturating_add(Weight::from_proof_size(192).saturating_mul(m.into()))
    }
    /// Storage: AdvisoryCommitteeMembership Members (r:1 w:1)
    /// Proof: AdvisoryCommitteeMembership Members (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
    /// Storage: AdvisoryCommittee Proposals (r:1 w:0)
    /// Proof Skipped: AdvisoryCommittee Proposals (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: AdvisoryCommitteeMembership Prime (r:1 w:0)
    /// Proof: AdvisoryCommitteeMembership Prime (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
    /// Storage: AdvisoryCommittee Members (r:0 w:1)
    /// Proof Skipped: AdvisoryCommittee Members (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: AdvisoryCommittee Prime (r:0 w:1)
    /// Proof Skipped: AdvisoryCommittee Prime (max_values: Some(1), max_size: None, mode: Measured)
    fn swap_member(m: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `341 + m * (64 ±0)`
        //  Estimated: `5739 + m * (192 ±0)`
        // Minimum execution time: 33_530 nanoseconds.
        Weight::from_parts(40_652_820, 5739)
            // Standard Error: 5_364
            .saturating_add(Weight::from_ref_time(76_219).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
            .saturating_add(Weight::from_proof_size(192).saturating_mul(m.into()))
    }
    /// Storage: AdvisoryCommitteeMembership Members (r:1 w:1)
    /// Proof: AdvisoryCommitteeMembership Members (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
    /// Storage: AdvisoryCommittee Proposals (r:1 w:0)
    /// Proof Skipped: AdvisoryCommittee Proposals (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: AdvisoryCommitteeMembership Prime (r:1 w:0)
    /// Proof: AdvisoryCommitteeMembership Prime (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
    /// Storage: AdvisoryCommittee Members (r:0 w:1)
    /// Proof Skipped: AdvisoryCommittee Members (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: AdvisoryCommittee Prime (r:0 w:1)
    /// Proof Skipped: AdvisoryCommittee Prime (max_values: Some(1), max_size: None, mode: Measured)
    fn reset_member(m: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `341 + m * (64 ±0)`
        //  Estimated: `5739 + m * (192 ±0)`
        // Minimum execution time: 32_460 nanoseconds.
        Weight::from_parts(38_785_548, 5739)
            // Standard Error: 6_043
            .saturating_add(Weight::from_ref_time(278_143).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
            .saturating_add(Weight::from_proof_size(192).saturating_mul(m.into()))
    }
    /// Storage: AdvisoryCommitteeMembership Members (r:1 w:1)
    /// Proof: AdvisoryCommitteeMembership Members (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
    /// Storage: AdvisoryCommittee Proposals (r:1 w:0)
    /// Proof Skipped: AdvisoryCommittee Proposals (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: AdvisoryCommitteeMembership Prime (r:1 w:1)
    /// Proof: AdvisoryCommitteeMembership Prime (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
    /// Storage: AdvisoryCommittee Members (r:0 w:1)
    /// Proof Skipped: AdvisoryCommittee Members (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: AdvisoryCommittee Prime (r:0 w:1)
    /// Proof Skipped: AdvisoryCommittee Prime (max_values: Some(1), max_size: None, mode: Measured)
    fn change_key(m: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `341 + m * (64 ±0)`
        //  Estimated: `5739 + m * (192 ±0)`
        // Minimum execution time: 34_520 nanoseconds.
        Weight::from_parts(43_530_038, 5739)
            // Standard Error: 10_675
            .saturating_add(Weight::from_ref_time(71_445).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
            .saturating_add(Weight::from_proof_size(192).saturating_mul(m.into()))
    }
    /// Storage: AdvisoryCommitteeMembership Members (r:1 w:0)
    /// Proof: AdvisoryCommitteeMembership Members (max_values: Some(1), max_size: Some(3202), added: 3697, mode: MaxEncodedLen)
    /// Storage: AdvisoryCommitteeMembership Prime (r:0 w:1)
    /// Proof: AdvisoryCommitteeMembership Prime (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
    /// Storage: AdvisoryCommittee Prime (r:0 w:1)
    /// Proof Skipped: AdvisoryCommittee Prime (max_values: Some(1), max_size: None, mode: Measured)
    fn set_prime(m: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `136 + m * (32 ±0)`
        //  Estimated: `3833 + m * (32 ±0)`
        // Minimum execution time: 15_240 nanoseconds.
        Weight::from_parts(18_236_079, 3833)
            // Standard Error: 2_638
            .saturating_add(Weight::from_ref_time(21_989).saturating_mul(m.into()))
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
            .saturating_add(Weight::from_proof_size(32).saturating_mul(m.into()))
    }
    /// Storage: AdvisoryCommitteeMembership Prime (r:0 w:1)
    /// Proof: AdvisoryCommitteeMembership Prime (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
    /// Storage: AdvisoryCommittee Prime (r:0 w:1)
    /// Proof Skipped: AdvisoryCommittee Prime (max_values: Some(1), max_size: None, mode: Measured)
    fn clear_prime(_m: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_590 nanoseconds.
        Weight::from_ref_time(6_974_592).saturating_add(T::DbWeight::get().writes(2_u64))
    }
}
