// Copyright 2022-2024 Forecasting Technologies LTD.
// Copyright 2021-2022 Zeitgeist PM LLC.
//
// This file is part of Zeitgeist.
//
// Zeitgeist is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// Zeitgeist is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Zeitgeist. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for pallet_democracy
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: `2024-07-24`, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `zeitgeist-benchmark`, CPU: `AMD EPYC 7601 32-Core Processor`
//! EXECUTION: ``, WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/production/zeitgeist
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_democracy
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --template=./misc/frame_weight_template.hbs
// --header=./HEADER_GPL3
// --output=./runtime/common/src/weights/

#![allow(unused_parens)]
#![allow(unused_imports)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for pallet_democracy (automatically generated)
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_democracy::weights::WeightInfo for WeightInfo<T> {
    /// Storage: `Democracy::PublicPropCount` (r:1 w:1)
    /// Proof: `Democracy::PublicPropCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::PublicProps` (r:1 w:1)
    /// Proof: `Democracy::PublicProps` (`max_values`: Some(1), `max_size`: Some(16702), added: 17197, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::Blacklist` (r:1 w:0)
    /// Proof: `Democracy::Blacklist` (`max_values`: None, `max_size`: Some(3242), added: 5717, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::DepositOf` (r:0 w:1)
    /// Proof: `Democracy::DepositOf` (`max_values`: None, `max_size`: Some(3230), added: 5705, mode: `MaxEncodedLen`)
    fn propose() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `4772`
        //  Estimated: `18187`
        // Minimum execution time: 94_250 nanoseconds.
        Weight::from_parts(106_040_000, 18187)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }
    /// Storage: `Democracy::DepositOf` (r:1 w:1)
    /// Proof: `Democracy::DepositOf` (`max_values`: None, `max_size`: Some(3230), added: 5705, mode: `MaxEncodedLen`)
    fn second() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `3527`
        //  Estimated: `6695`
        // Minimum execution time: 79_460 nanoseconds.
        Weight::from_parts(83_551_000, 6695)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `Democracy::ReferendumInfoOf` (r:1 w:1)
    /// Proof: `Democracy::ReferendumInfoOf` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::VotingOf` (r:1 w:1)
    /// Proof: `Democracy::VotingOf` (`max_values`: None, `max_size`: Some(3799), added: 6274, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Locks` (r:1 w:1)
    /// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Freezes` (r:1 w:0)
    /// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
    fn vote_new() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `3415`
        //  Estimated: `7264`
        // Minimum execution time: 119_831 nanoseconds.
        Weight::from_parts(125_030_000, 7264)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(3))
    }
    /// Storage: `Democracy::ReferendumInfoOf` (r:1 w:1)
    /// Proof: `Democracy::ReferendumInfoOf` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::VotingOf` (r:1 w:1)
    /// Proof: `Democracy::VotingOf` (`max_values`: None, `max_size`: Some(3799), added: 6274, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Locks` (r:1 w:1)
    /// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Freezes` (r:1 w:0)
    /// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
    fn vote_existing() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `3437`
        //  Estimated: `7264`
        // Minimum execution time: 98_820 nanoseconds.
        Weight::from_parts(131_651_000, 7264)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(3))
    }
    /// Storage: `Democracy::ReferendumInfoOf` (r:1 w:1)
    /// Proof: `Democracy::ReferendumInfoOf` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::Cancellations` (r:1 w:1)
    /// Proof: `Democracy::Cancellations` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::MetadataOf` (r:1 w:1)
    /// Proof: `Democracy::MetadataOf` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
    fn emergency_cancel() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `341`
        //  Estimated: `3674`
        // Minimum execution time: 52_690 nanoseconds.
        Weight::from_parts(54_040_000, 3674)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }
    /// Storage: `Democracy::PublicProps` (r:1 w:1)
    /// Proof: `Democracy::PublicProps` (`max_values`: Some(1), `max_size`: Some(16702), added: 17197, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::DepositOf` (r:1 w:1)
    /// Proof: `Democracy::DepositOf` (`max_values`: None, `max_size`: Some(3230), added: 5705, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:2 w:2)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::MetadataOf` (r:3 w:1)
    /// Proof: `Democracy::MetadataOf` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::NextExternal` (r:1 w:1)
    /// Proof: `Democracy::NextExternal` (`max_values`: Some(1), `max_size`: Some(132), added: 627, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::ReferendumInfoOf` (r:1 w:1)
    /// Proof: `Democracy::ReferendumInfoOf` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::Blacklist` (r:0 w:1)
    /// Proof: `Democracy::Blacklist` (`max_values`: None, `max_size`: Some(3242), added: 5717, mode: `MaxEncodedLen`)
    fn blacklist() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `6171`
        //  Estimated: `18187`
        // Minimum execution time: 214_781 nanoseconds.
        Weight::from_parts(226_251_000, 18187)
            .saturating_add(T::DbWeight::get().reads(9))
            .saturating_add(T::DbWeight::get().writes(8))
    }
    /// Storage: `Democracy::NextExternal` (r:1 w:1)
    /// Proof: `Democracy::NextExternal` (`max_values`: Some(1), `max_size`: Some(132), added: 627, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::Blacklist` (r:1 w:0)
    /// Proof: `Democracy::Blacklist` (`max_values`: None, `max_size`: Some(3242), added: 5717, mode: `MaxEncodedLen`)
    fn external_propose() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `3387`
        //  Estimated: `6707`
        // Minimum execution time: 28_680 nanoseconds.
        Weight::from_parts(29_660_000, 6707)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `Democracy::NextExternal` (r:0 w:1)
    /// Proof: `Democracy::NextExternal` (`max_values`: Some(1), `max_size`: Some(132), added: 627, mode: `MaxEncodedLen`)
    fn external_propose_majority() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 6_580 nanoseconds.
        Weight::from_parts(7_150_000, 0).saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `Democracy::NextExternal` (r:0 w:1)
    /// Proof: `Democracy::NextExternal` (`max_values`: Some(1), `max_size`: Some(132), added: 627, mode: `MaxEncodedLen`)
    fn external_propose_default() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 6_760 nanoseconds.
        Weight::from_parts(7_100_000, 0).saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `Democracy::NextExternal` (r:1 w:1)
    /// Proof: `Democracy::NextExternal` (`max_values`: Some(1), `max_size`: Some(132), added: 627, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::ReferendumCount` (r:1 w:1)
    /// Proof: `Democracy::ReferendumCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::MetadataOf` (r:1 w:2)
    /// Proof: `Democracy::MetadataOf` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::ReferendumInfoOf` (r:0 w:1)
    /// Proof: `Democracy::ReferendumInfoOf` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
    fn fast_track() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `253`
        //  Estimated: `3518`
        // Minimum execution time: 54_810 nanoseconds.
        Weight::from_parts(55_750_000, 3518)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(5))
    }
    /// Storage: `Democracy::NextExternal` (r:1 w:1)
    /// Proof: `Democracy::NextExternal` (`max_values`: Some(1), `max_size`: Some(132), added: 627, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::Blacklist` (r:1 w:1)
    /// Proof: `Democracy::Blacklist` (`max_values`: None, `max_size`: Some(3242), added: 5717, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::MetadataOf` (r:1 w:1)
    /// Proof: `Democracy::MetadataOf` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
    fn veto_external() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `3490`
        //  Estimated: `6707`
        // Minimum execution time: 59_521 nanoseconds.
        Weight::from_parts(60_930_000, 6707)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }
    /// Storage: `Democracy::PublicProps` (r:1 w:1)
    /// Proof: `Democracy::PublicProps` (`max_values`: Some(1), `max_size`: Some(16702), added: 17197, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::DepositOf` (r:1 w:1)
    /// Proof: `Democracy::DepositOf` (`max_values`: None, `max_size`: Some(3230), added: 5705, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:2 w:2)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::MetadataOf` (r:1 w:1)
    /// Proof: `Democracy::MetadataOf` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
    fn cancel_proposal() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `6074`
        //  Estimated: `18187`
        // Minimum execution time: 186_500 nanoseconds.
        Weight::from_parts(203_851_000, 18187)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(5))
    }
    /// Storage: `Democracy::MetadataOf` (r:1 w:1)
    /// Proof: `Democracy::MetadataOf` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::ReferendumInfoOf` (r:0 w:1)
    /// Proof: `Democracy::ReferendumInfoOf` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
    fn cancel_referendum() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `238`
        //  Estimated: `3518`
        // Minimum execution time: 40_041 nanoseconds.
        Weight::from_parts(41_300_000, 3518)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    /// Storage: `Democracy::LowestUnbaked` (r:1 w:1)
    /// Proof: `Democracy::LowestUnbaked` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::ReferendumCount` (r:1 w:0)
    /// Proof: `Democracy::ReferendumCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::ReferendumInfoOf` (r:99 w:0)
    /// Proof: `Democracy::ReferendumInfoOf` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
    /// The range of component `r` is `[0, 99]`.
    fn on_initialize_base(r: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `211 + r * (94 ±0)`
        //  Estimated: `1489 + r * (2684 ±0)`
        // Minimum execution time: 15_640 nanoseconds.
        Weight::from_parts(16_300_000, 1489)
            // Standard Error: 24_194
            .saturating_add(Weight::from_parts(6_717_090, 0).saturating_mul(r.into()))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(r.into())))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(Weight::from_parts(0, 2684).saturating_mul(r.into()))
    }
    /// Storage: `Democracy::LowestUnbaked` (r:1 w:1)
    /// Proof: `Democracy::LowestUnbaked` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::ReferendumCount` (r:1 w:0)
    /// Proof: `Democracy::ReferendumCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::LastTabledWasExternal` (r:1 w:0)
    /// Proof: `Democracy::LastTabledWasExternal` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::NextExternal` (r:1 w:0)
    /// Proof: `Democracy::NextExternal` (`max_values`: Some(1), `max_size`: Some(132), added: 627, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::PublicProps` (r:1 w:0)
    /// Proof: `Democracy::PublicProps` (`max_values`: Some(1), `max_size`: Some(16702), added: 17197, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::ReferendumInfoOf` (r:99 w:0)
    /// Proof: `Democracy::ReferendumInfoOf` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
    /// The range of component `r` is `[0, 99]`.
    fn on_initialize_base_with_launch_period(r: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `211 + r * (94 ±0)`
        //  Estimated: `18187 + r * (2684 ±0)`
        // Minimum execution time: 21_570 nanoseconds.
        Weight::from_parts(21_702_657, 18187)
            // Standard Error: 27_834
            .saturating_add(Weight::from_parts(6_702_723, 0).saturating_mul(r.into()))
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(r.into())))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(Weight::from_parts(0, 2684).saturating_mul(r.into()))
    }
    /// Storage: `Democracy::VotingOf` (r:3 w:3)
    /// Proof: `Democracy::VotingOf` (`max_values`: None, `max_size`: Some(3799), added: 6274, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::ReferendumInfoOf` (r:99 w:99)
    /// Proof: `Democracy::ReferendumInfoOf` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Locks` (r:1 w:1)
    /// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Freezes` (r:1 w:0)
    /// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
    /// The range of component `r` is `[0, 99]`.
    fn delegate(r: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `779 + r * (116 ±0)`
        //  Estimated: `19812 + r * (2684 ±0)`
        // Minimum execution time: 77_540 nanoseconds.
        Weight::from_parts(78_180_523, 19812)
            // Standard Error: 62_728
            .saturating_add(Weight::from_parts(8_933_951, 0).saturating_mul(r.into()))
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(r.into())))
            .saturating_add(T::DbWeight::get().writes(4))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(r.into())))
            .saturating_add(Weight::from_parts(0, 2684).saturating_mul(r.into()))
    }
    /// Storage: `Democracy::VotingOf` (r:2 w:2)
    /// Proof: `Democracy::VotingOf` (`max_values`: None, `max_size`: Some(3799), added: 6274, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::ReferendumInfoOf` (r:99 w:99)
    /// Proof: `Democracy::ReferendumInfoOf` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
    /// The range of component `r` is `[0, 99]`.
    fn undelegate(r: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `468 + r * (116 ±0)`
        //  Estimated: `13538 + r * (2684 ±0)`
        // Minimum execution time: 42_001 nanoseconds.
        Weight::from_parts(44_467_605, 13538)
            // Standard Error: 42_007
            .saturating_add(Weight::from_parts(8_358_722, 0).saturating_mul(r.into()))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(r.into())))
            .saturating_add(T::DbWeight::get().writes(2))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(r.into())))
            .saturating_add(Weight::from_parts(0, 2684).saturating_mul(r.into()))
    }
    /// Storage: `Democracy::PublicProps` (r:0 w:1)
    /// Proof: `Democracy::PublicProps` (`max_values`: Some(1), `max_size`: Some(16702), added: 17197, mode: `MaxEncodedLen`)
    fn clear_public_proposals() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 6_970 nanoseconds.
        Weight::from_parts(7_250_000, 0).saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `Democracy::VotingOf` (r:1 w:1)
    /// Proof: `Democracy::VotingOf` (`max_values`: None, `max_size`: Some(3799), added: 6274, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Locks` (r:1 w:1)
    /// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Freezes` (r:1 w:0)
    /// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
    /// The range of component `r` is `[0, 99]`.
    fn unlock_remove(r: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `500`
        //  Estimated: `7264`
        // Minimum execution time: 46_810 nanoseconds.
        Weight::from_parts(73_459_464, 7264)
            // Standard Error: 9_303
            .saturating_add(Weight::from_parts(355_260, 0).saturating_mul(r.into()))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(3))
    }
    /// Storage: `Democracy::VotingOf` (r:1 w:1)
    /// Proof: `Democracy::VotingOf` (`max_values`: None, `max_size`: Some(3799), added: 6274, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Locks` (r:1 w:1)
    /// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Freezes` (r:1 w:0)
    /// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
    /// The range of component `r` is `[0, 99]`.
    fn unlock_set(r: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `501 + r * (22 ±0)`
        //  Estimated: `7264`
        // Minimum execution time: 57_700 nanoseconds.
        Weight::from_parts(73_683_809, 7264)
            // Standard Error: 10_335
            .saturating_add(Weight::from_parts(391_304, 0).saturating_mul(r.into()))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(3))
    }
    /// Storage: `Democracy::ReferendumInfoOf` (r:1 w:1)
    /// Proof: `Democracy::ReferendumInfoOf` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::VotingOf` (r:1 w:1)
    /// Proof: `Democracy::VotingOf` (`max_values`: None, `max_size`: Some(3799), added: 6274, mode: `MaxEncodedLen`)
    /// The range of component `r` is `[1, 100]`.
    fn remove_vote(r: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `707 + r * (26 ±0)`
        //  Estimated: `7264`
        // Minimum execution time: 32_310 nanoseconds.
        Weight::from_parts(42_608_741, 7264)
            // Standard Error: 8_632
            .saturating_add(Weight::from_parts(320_539, 0).saturating_mul(r.into()))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    /// Storage: `Democracy::ReferendumInfoOf` (r:1 w:1)
    /// Proof: `Democracy::ReferendumInfoOf` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::VotingOf` (r:1 w:1)
    /// Proof: `Democracy::VotingOf` (`max_values`: None, `max_size`: Some(3799), added: 6274, mode: `MaxEncodedLen`)
    /// The range of component `r` is `[1, 100]`.
    fn remove_other_vote(r: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `707 + r * (26 ±0)`
        //  Estimated: `7264`
        // Minimum execution time: 27_850 nanoseconds.
        Weight::from_parts(38_259_109, 7264)
            // Standard Error: 6_531
            .saturating_add(Weight::from_parts(367_033, 0).saturating_mul(r.into()))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    /// Storage: `Democracy::NextExternal` (r:1 w:0)
    /// Proof: `Democracy::NextExternal` (`max_values`: Some(1), `max_size`: Some(132), added: 627, mode: `MaxEncodedLen`)
    /// Storage: `Preimage::StatusFor` (r:1 w:0)
    /// Proof: `Preimage::StatusFor` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::MetadataOf` (r:0 w:1)
    /// Proof: `Democracy::MetadataOf` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
    fn set_external_metadata() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `323`
        //  Estimated: `3556`
        // Minimum execution time: 37_840 nanoseconds.
        Weight::from_parts(38_590_000, 3556)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `Democracy::NextExternal` (r:1 w:0)
    /// Proof: `Democracy::NextExternal` (`max_values`: Some(1), `max_size`: Some(132), added: 627, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::MetadataOf` (r:1 w:1)
    /// Proof: `Democracy::MetadataOf` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
    fn clear_external_metadata() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `253`
        //  Estimated: `3518`
        // Minimum execution time: 34_190 nanoseconds.
        Weight::from_parts(35_360_000, 3518)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `Democracy::PublicProps` (r:1 w:0)
    /// Proof: `Democracy::PublicProps` (`max_values`: Some(1), `max_size`: Some(16702), added: 17197, mode: `MaxEncodedLen`)
    /// Storage: `Preimage::StatusFor` (r:1 w:0)
    /// Proof: `Preimage::StatusFor` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::MetadataOf` (r:0 w:1)
    /// Proof: `Democracy::MetadataOf` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
    fn set_proposal_metadata() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `4855`
        //  Estimated: `18187`
        // Minimum execution time: 79_700 nanoseconds.
        Weight::from_parts(93_760_000, 18187)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `Democracy::PublicProps` (r:1 w:0)
    /// Proof: `Democracy::PublicProps` (`max_values`: Some(1), `max_size`: Some(16702), added: 17197, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::MetadataOf` (r:1 w:1)
    /// Proof: `Democracy::MetadataOf` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
    fn clear_proposal_metadata() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `4789`
        //  Estimated: `18187`
        // Minimum execution time: 77_470 nanoseconds.
        Weight::from_parts(88_080_000, 18187)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `Preimage::StatusFor` (r:1 w:0)
    /// Proof: `Preimage::StatusFor` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::MetadataOf` (r:0 w:1)
    /// Proof: `Democracy::MetadataOf` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
    fn set_referendum_metadata() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `144`
        //  Estimated: `3556`
        // Minimum execution time: 29_750 nanoseconds.
        Weight::from_parts(30_401_000, 3556)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `Democracy::ReferendumInfoOf` (r:1 w:0)
    /// Proof: `Democracy::ReferendumInfoOf` (`max_values`: None, `max_size`: Some(209), added: 2684, mode: `MaxEncodedLen`)
    /// Storage: `Democracy::MetadataOf` (r:1 w:1)
    /// Proof: `Democracy::MetadataOf` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
    fn clear_referendum_metadata() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `273`
        //  Estimated: `3674`
        // Minimum execution time: 38_380 nanoseconds.
        Weight::from_parts(39_540_000, 3674)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}
