name: Copyright

on:
  pull_request:
    types: [ labeled ]
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  copyright:
    name: Copyright Notices
    if: |
      github.event_name == 'pull_request' && 
        (contains(github.event.pull_request.labels.*.name, 's:review-needed') ||
        contains(github.event.pull_request.labels.*.name, 's:accepted')) ||
      github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install check-license and dependencies
        run: |
          pip install scripts/check-license
          pip install -r scripts/check-license/requirements.txt
      - name: Query files changed
        id: files_changed
        uses: Ana06/get-changed-files@v1.2
        with:
          filter: '*.rs$'
      - name: Check copyright notices
        run: check-license ${{ steps.files_changed.outputs.added_modified }}
