name: Coverage

on:
  pull_request:
    types: [ labeled ]
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Coverage
    if: |
      github.event_name == 'pull_request' && 
        (contains(github.event.pull_request.labels.*.name, 's:review-needed') ||
        contains(github.event.pull_request.labels.*.name, 's:accepted')) ||
      github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      - name: Install rust toolchain
        run: rustup show

      - uses: actions-rs/install@v0.1
        with:
          crate: grcov
          use-tool-cache: false
      
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1

      - name: Generate coverage report
        run: ./scripts/tests/coverage.sh

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ runner.temp }}/zeitgeist-test-coverage.lcov
          fail_ci_if_error: true
          flags: tests
          verbose: true
          name: unit-tests
