name: Migration

on:
  workflow_dispatch:
    inputs:
      block:
        description: 'Block number'    
        required: true
jobs:
  migration:
    name: Test migration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install build tools
        run: ./scripts/init.sh

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - run: ./scripts/runtime-upgrade/test_runtime_upgrade.sh ${{ github.event.inputs.block }}
